### ISSUE TITLE
Data file not found

### ISSUE THREAD

**Issue by MaverickLegacy** [amineHorseman/facial-expression-recognition-svm#1]
I would like run and see the implementation but the 2013Landmarks+hog file with hog features are not found. It would be great if you could upload the file. Thank you.

**Comment by amineHorseman** [comment]
Hi, 

Indeed I didn't upload the hog features because of the large file size, but I just uploaded the script I used to extract the hog features and face's landmarks: [convert_fer2013_to_images_and_landmarks.py](https://github.com/amineHorseman/facial-expression-recognition-svm/blob/master/convert_fer2013_to_images_and_landmarks.py)

Make sure to set the constants in the beggining of the script according to your needs.

**Comment by MaverickLegacy** [comment]
Thank you.
