### ISSUE TITLE
sliding window

### ISSUE THREAD

**Issue by justyxl** [amineHorseman/facial-expression-recognition-svm#3]
Hello, I am a newcomer to research expression recognition.I want to know what sliding window is doing with the data.Why can IT improve the accuracy? Thank you in advance for your reply.

**Comment by amineHorseman** [comment]
Hi, 
Sliding window is not related to the expression recognition

When we use the sliding window, we choose to apply the HOG filter on a sub-region of the image (instead of the entire image), then we move the next region and apply the filter...etc. This operation is know as sliding window, because we are sliding the HOG filter throught different regions of the image.

Why this can improve the accuracy? Well, by sliding the HOG window we are focusing on a specific region  of the image, and at the end we got more features extracted because we applied the HOG filter several times. But of course, some of the features are redundant or useless, so the classification algorithm (in our cas SVM or CNN) have to learn to ignore those useless features and focus only on the ones that really describe the face's expression.
